# Avaliação Intermediária

NOME: **Alan Matheus Alves Barbosa**
E-MAIL: **alanm2@al.insper.edu.br**

Esta é a A.I. de Álgebra Linear e Teoria da Informação de 1s2023.



INSTRUÇÕES:

1. Faça todas as questões
1. Salve o notebook
1. Envie o notebook salvo no Blackboard

IMPORTANTE:

* Você pode consultar qualquer material ou IA, mas não qualquer colega ou pessoa humana, presente ou não na prova.
* O envio da prova será fechado às 17h45. Aqueles que não enviarem o material até este horário ficarão com zero.
* A prova vale um total de 10 pontos. As questões 1, 2, 3 e 4 têm, respectivamente, pesos 1, 2, 3 e 4.
* Os conceitos F, E, D, C, B, A serão mapeados para 0, 2, 4, 6, 8 e 10.
* Para todas as questões, usaremos a rubrica que segue anexa a esta prova. Há uma rubrica para a justificativa e uma rubrica para o código. A nota da questão é a menor entre as notas da justificativa e do código.


## Exercício 1

* Peso: 1 ponto

Dadas as matrizes:

$$
A = \begin{bmatrix} 1 & 3 &\\ 2 & 1 \end{bmatrix} \\

B = \begin{bmatrix} 2 & 3\\ 5 & 8 \end{bmatrix} \\

C = AB \\

D = BA 
$$

calcule:

$X = (ABC^{-1}BAD^{-1})^T \odot A$



---------------------------------------------------
Implementei diretamente a equação.

---------------------------------------------------

In [9]:
import numpy as np

A = np.array([[1,3], [2,1]])
B = np.array([[2,3], [5,8]])
C = A@B
D = B@A

x = (((A@B@np.linalg.inv(C))@B@A@(np.linalg.inv(D))).T )*A    #Solução da equação, no final uma multiplicação ponto a ponto.
print(x)


[[ 1.00000000e+00 -1.06581410e-15]
 [ 2.04281037e-15  1.00000000e+00]]


# Exercício 2

* Peso: 2 pontos

Tenho uma matriz $X$ que contém todas as posições $(i,j)$ de pixels de uma figura de 600x600 pixels, sendo cada pixel armazenado em uma coluna e cada dimensão armazenada em uma linha. Qual é a matriz que permite encolher essa figura de forma que cada uma de suas dimensões seja reduzida pela metade, mas seu centro seja preservado? Se precisar, use coordenadas homogêneas!


-------------------------------------------------------------
Primeiro, o centro da imagem é definido como o ponto $(300, 300)$ usando a variável C.

Em seguida, são criadas três matrizes de transformação: T1, S e T2.

A matriz T1 é uma matriz de translação que move a origem do sistema de coordenadas para o centro da imagem, representado por C. Isso é feito subtraindo as coordenadas de C das coordenadas originais.

A matriz S é uma matriz de escala que reduz as dimensões da imagem pela metade. Isso é feito definindo os valores da diagonal principal como $0,5$.

A matriz T2 é uma matriz de translação que move a origem do sistema de coordenadas de volta para a posição original, adicionando as coordenadas de C às coordenadas resultantes.

Por fim, a matriz de transformação resultante é calculada multiplicando as três matrizes: T2, S e T1.

A matriz de transformação resultante é armazenada na variável Transformação.

-------------------------------------------------------------

In [51]:
import numpy as np


#centro da imagem
C = (300,300)

#matrizes de transformação
T1 = np.array([[1, 0, -C[0]], [0, 1, -C[1]], [0, 0, 1]])  #T1 -> transformação 1
S = np.array([[0.5, 0, 0], [0, 0.5, 0], [0, 0, 1]])       #S -> escala
T2 = np.array([[1, 0, C[0]], [0, 1, C[1]], [0, 0, 1]])    #T2 -> transformação 2

#matriz de transformação resultante
Transformação = T2@S@T1

print(f'O resultado final é:\n {Transformação}')

O resultado final é:
 [[  0.5   0.  150. ]
 [  0.    0.5 150. ]
 [  0.    0.    1. ]]


# Exercício 3

* Peso: 3 pontos

Algumas carteiras de investimento deram os seguintes retornos:

* 100 ações da empresa E1 e 200 ações da E2 deram retorno de R$100,00,
* 1000 ações da empresa E1 e 2000 ações da E2 deram retorno de R$1000,00,
* 200 ações da empresa E2 e 300 da E3 deram retorno de R$500,00 
* 400 ações da empresa E2 e 600 da E3 deram retorno de R$1000,00 
* 1000 ações da empresa E1 e 100 da E3 deram retorno de R$1500,00
* 2000 ações da empresa E1 e 200 da E3 deram retorno de R$3000,00 

*Usando estritamente formulações matriciais*, responda:
1. Qual é o retorno por ação de cada empresa?
1. Qual é o retorno de uma carteira com 100 ações da empresa E1, 200 da empresa E2 e 300 da E3?

----------------------------------------------
Na primeira parte, é criada a matriz matriz_valores_acoes com os valores dos retornos de cada empresa em cada carteira de investimento. Em seguida, é criado o vetor resultados com os valores totais de retorno de cada carteira de investimento. Utilizando a função np.linalg.solve, é possível resolver o sistema de equações formado pela matriz e pelo vetor e encontrar as soluções para o retorno por ação de cada empresa. O resultado é impresso na tela com a mensagem "Solução da 1".
Obs: Ignorei na conta as equações semelhantes, como: 
* 100 ações da empresa E1 e 200 ações da E2 deram retorno de R$100,00,
* 1000 ações da empresa E1 e 2000 ações da E2 deram retorno de R$1000,00,
Pois a segunda é igual a primeira multiplicada por 10.

Na segunda parte, é calculado o retorno de uma carteira específica com 100 ações da empresa E1, 200 ações da empresa E2 e 300 ações da empresa E3. Para isso, basta multiplicar a quantidade de ações de cada empresa pelo seu respectivo valor de retorno encontrado na primeira parte e somar os resultados. O resultado é impresso na tela com a mensagem "Solução da 2".

----------------------------------------------

In [60]:
import numpy as np
# 100*E1 + 200*E2 = 100
# 200*E2 + 300*E3 = 500
# 1000*E1 + 100*E3 = 1500

#SOLUÇÃO DA 1
matriz_valores_acoes = np.array([[100,200,0],[0,200,300],[1000,0,100]])
resultados = np.array([[100,500,1500]])
solucao = np.linalg.solve(matriz_valores_acoes, resultados.T)
print('Solução da 1')
print(solucao)

#SOLUÇÃO DA 2
print('Solução da 2')
print(solucao[0][0]*100 + solucao[1][0]*200 + solucao[2][0]*300)


print(f"Portanto, E1 = {solucao[0][0]}, E2 = {solucao[1][0]} e E3 = {solucao[2][0]}")



Solução da 1
[[ 1.32258065]
 [-0.16129032]
 [ 1.77419355]]
Solução da 2
632.258064516129
Portanto, E1 = 1.3225806451612903, E2 = -0.16129032258064513 e E3 = 1.7741935483870968


# Exercício 4

* Peso: 4 pontos

Uma maneira de fazer transformações em imagens é usar pontos de referência. Por exemplo, podemos definir pontos de referência em um rosto como o centro de cada um dos olhos, a ponta do nariz e o ponto inferior do queixo. Daí então, encontramos onde esses pontos estão na imagem de origem, e escolhemos (como quisermos) onde os pontos estão na imagem de destino. Encontramos a transformação linear que realiza esse mapeamento, e então aplicamos essa mesma transformação para todos os pontos da imagem, isto é:

$$
Xd = T X,
$$

onde $Xd$ é uma matriz com pontos na imagem de destino, $X$ é uma matriz com pontos na imagem de origem, e $T$ é uma transformação linear.

Num rosto, em uma imagem que está mapeada no plano cartesiano (isto é, no plano usual $x,y$ e não numa matriz de pixels), encontramos:

* O olho esquerdo em $(-2, 3)$,
* o olho direito em $(2, 3)$
* A ponta do nariz em $(0,0)$
* O ponto inferior do queixo em $(0, -3)$

O rosto foi mapeado usando uma transformação linear de forma que os pontos de referência foram deslocados para:

* O olho esquerdo em $(-6, 2)$,
* o olho direito em $(6, 1)$
* A ponta do nariz em $(3, 0)$

Usando formulações matriciais, responda: qual é a distância entre o ponto inferior do queixo e a ponta do nariz no novo mapeamento?


-------------------------------------------------------------------------------------------------------------------------
Inicialmente, eu calculei a matriz X formada pelos pontos na base X, ignorando inicialmente o ponto inferior do queixo, incluí uma linha de 1's para termos a matriz quadrada que seria transformada em inversa posteriormente (necessita ser quadrada).
Tendo então a matriz X: [[-2, 2, 0], [3, 3, 0], [1, 1, 1]]

Logo após, calculei a matriz Xd, da mesma forma, ignorando o ponto inferior do queixo.
Tendo então a matriz Xd: [[-6, 6, 3], [2, 1, 0], [1, 1, 1]]

Com isso, posso obter a matriz de transformação: $$ T = Xd*X^{-1} $$

Possuindo a matriz transformação, ignorei agora o ponto referente ao nariz e achei novamente o Xd

[[-6.   6.   6. ]
 [ 2.   1.  -1.5]
 [ 1.   1.   1. ]]

Com o novo Xd e printando a resposta, eu poderia já ver a nova localização do ponto inferior do queixo, no caso seria (6,-1.5) 

Agora, usando a distância entre pontos, calculamos a distância, que no caso seria de: 3.354 aproximadamente.

-------------------------------------------------------------------------------------------------------------------------

In [49]:
import numpy as np

# Matriz X com os pontos de referência na imagem original
X = np.array([[-2, 2, 0], [3, 3, 0], [1, 1, 1]])

# Matriz Xd com os pontos de referência na imagem de destino
Xd = np.array([[-6, 6, 3], [2, 1, 0], [1, 1, 1]])

# Calculando a matriz de transformação T
T = Xd@(np.linalg.inv(X))

# ponto anterior em X do queixo: (0,-3)

xd_new = T@np.array([[-2, 2, 0], [3, 3, -3], [1, 1, 1]])

#Analisando, a nova coordenada do queixo é (6,-1.5)
#Agora, calculando a distância entre o ponto inferior do queixo e a ponta do nariz na nova coordenada. pontos: (3,0), (6,-1.5)
dist = np.sqrt((6-3)**2 + (-1.5-0)**2)
print(dist)
print(f'A nova distância entre eles é {dist:.3f} unidades')

[[-6.   6.   6. ]
 [ 2.   1.  -1.5]
 [ 1.   1.   1. ]]
3.3541019662496847
A nova distância entre eles é 3.354 unidades
